### ISSUE TITLE
LED HAT problem

### ISSUE THREAD

**Issue by lainol** [guido-visser/vMix-M5Stick-Tally-Light#19] opened 2021-01-09 16:25 UTC
- installed lib FastLED version 3.004.000

- uncommented "#include "plugins/LED_HAT.h";"

- ...\FastLED-master\src/fastspi.h:135:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output ---     pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

- compiled and upload correct

- no light from hex led

what am I doing wrong? I have the HEX LED hat from m5stack

**Comment by IvorOrr** [comment] 2021-01-12 07:41
Since the SK6812 does not use SPI this is not the cause of your issue and normal FastLED behavior.
Could it be that you forgot to uncomment the other lines?

    // M5TallyLEDHat ledHat;  
    //ledHat.onLive ();  
    //ledHat.onPre ();  
    //ledHat.onSafe ();

k_PLUGINMANAGER.h is intended to be used as a point at which you can call up the functionality of additional accessories when the tally changes its status to "live", "pre" or "safe".

**Comment by guido-visser** [comment] 2021-01-12 07:54
The error that you point out is not the error that is causing the issue. the SPI error always shows up when using the FastLED library. Can you give more error output, so that I can investigate?

**Comment by lainol** [comment] 2021-01-12 20:16
I am so dumb... didn't get attention to the other commented lines as IvorOrr pointed. Sorry for the wasted time...

Another great solution instead hex led is hook up an atom matrix (previously configured as independet tally, but only for program) with the grove 4 pin connector, easier for 3d printed mount. Just few bucks more but more usefull

Thank you so much for this project, really usefull for low budget productions.

**Comment by guido-visser** [comment] 2021-01-13 08:33
You're very welcome. I'm planning on working on it soon again in regards to Tally Arbiter and the integration thereof. I'll close this issue for now.

**Closed by guido-visser** 2021-01-13 08:33 UTC
